### ISSUE TITLE
EOF error returned for a basic Do method use case

### ISSUE THREAD

**Issue by sanggonlee** [gomodule/redigo#390]
## Precondition

Using redis docker image 5.0.3, configured with docker-compose like the following.
```yaml
version: '3'
services:
  redis:
    container_name: "my_redis"
    image: "redis:5.0.3"
    ports:
    - "9100:9100"
```

## Problem

When executing the `redis.Conn.Do` method, consistently getting `EOF` error, even though the issue doesn't occur when I run the command on the redis server directly. At best, `EOF` is not a very meaningful error message in this context.

## Reproducible Scenario

I was facing this in a very basic use case for `SET` command. Below is the minimal code example.

```go
package main

import "github.com/gomodule/redigo/redis"

func main() {
	conn, err := redis.Dial("tcp", "localhost:9100")
	if err != nil {
		panic(err)
	}

	defer conn.Close()

	_, err = conn.Do("SET", "foo", "bar")
	if err != nil {
		panic(err)  // <------ Panics here, the error returned is "EOF"
	}
}
```
